apiVersion: v1
kind: Pod
metadata:
  name: demo-node-app
  labels:
    app: demo-node-app
spec:
  containers:
    - name: demo-node-app
      image: demo-node-app:latest
      imagePullPolicy: Never          # use locally built image in Minikube
      ports:
        - containerPort: 3000
      env:
        - name: PORT
          value: "3000"
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi